export const menu = [
  {
    // APPETIZERS
    menuSectionName: "CHINESE HERE - APPTIZERS 头盘(前菜)",
    menuSectionItems: [
      {
        id: 1,
        name: "Three Kind Appetizer Combinations",
        price: 32.8,
        isSpicy: true,
        menuItemNumber: 1,
        chineseTranslation: "椒盐三拼",
      },
      {
        id: 2,
        name: "New King Do Apptizer Combinations",
        price: 36.8,
        isSpicy: false,
        menuItemNumber: 2,
        chineseTranslation: "新京都大拼盘",
      },
      {
        id: 3,
        name: "Braised Crispy Squab",
        price: -1, // -1 is considered as market price
        isSpicy: false,
        menuItemNumber: 3,
        chineseTranslation: "红烧乳鸽王",
      },
      {
        id: 4,
        name: "D.F. Crab Claws Wrapper with Minced Shrimp",
        price: 6.5,
        isSpicy: false,
        menuItemNumber: 4,
        chineseTranslation: "白花酿蟹钳",
      },
      {
        id: 5,
        name: "Cold Marinated Jellyfish and Pork Hock",
        price: 19.95,
        isSpicy: false,
        menuItemNumber: 5,
        chineseTranslation: "海蜇熏蹄",
      },
      {
        id: 6,
        name: "Deep-Fried Assorted Meat Combinations",
        price: 28.8,
        isSpicy: false,
        menuItemNumber: 6,
        chineseTranslation: "酥炸拼盘",
      },
      {
        id: 7,
        name: "Lettuce Wrap (Chicken)",
        price: 20.95,
        isSpicy: false,
        menuItemNumber: 7,
        chineseTranslation: "鸡",
      },
      {
        id: 8,
        name: "Lettuce Wrap (Beef)",
        price: 20.95,
        isSpicy: false,
        menuItemNumber: 7,
        chineseTranslation: "牛肉",
      },
      {
        id: 9,
        name: "Lettuce Wrap (Seafood)",
        price: 22.95,
        isSpicy: false,
        menuItemNumber: 7,
        chineseTranslation: "海鲜",
      },
      {
        id: 10,
        name: "Spring Roll (1pc)",
        price: 1.65,
        isSpicy: false,
        menuItemNumber: 8,
        chineseTranslation: "炸春卷",
      },
      {
        id: 11,
        name: "Deep-Fried Wonton",
        price: 9.5,
        isSpicy: false,
        menuItemNumber: 9,
        chineseTranslation: "炸云吞",
      },
      {
        id: 12,
        name: "B.B.Q Pork",
        price: 8.95,
        isSpicy: false,
        menuItemNumber: 10,
        chineseTranslation: "蜜汁叉烧",
      },
    ],
  },
  {
    menuSectionName: "CHINESE HERE - SOUPS 汤羹类",
    menuSectionItems: [
      {
        id: 13,
        name: "Szechuan Hot-and-Sour Soup",
        price: 10.5,
        isSpicy: true,
        menuItemNumber: 11,
        chineseTranslation: "四川酸辣汤",
      },
      {
        id: 14,
        name: "Crabmeat with Fish Maw Soup (S)",
        price: 13.95,
        isSpicy: false,
        menuItemNumber: 12,
        chineseTranslation: "蟹肉鱼肚羹",
      },
      {
        id: 15,
        name: "Crabmeat with Fish Maw Soup (L)",
        price: 13.95,
        isSpicy: false,
        menuItemNumber: 12,
        chineseTranslation: "蟹肉鱼肚羹",
      },
      {
        id: 16,
        name: "Crabmeat with Cream Corn Soup",
        price: 12.5,
        isSpicy: false,
        menuItemNumber: 13,
        chineseTranslation: "蟹肉粟米羹",
      },
      {
        id: 17,
        name: "Minced Chicken and Cream Corn Soup",
        price: 10.5,
        isSpicy: false,
        menuItemNumber: 14,
        chineseTranslation: "鸡茸素米羹",
      },
      {
        id: 18,
        name: "Wonton Soup",
        price: 10.95,
        isSpicy: false,
        menuItemNumber: 15,
        chineseTranslation: "鲜虾云吞汤",
      },
      {
        id: 19,
        name: "War Wonton Soup (Large)",
        price: 18.95,
        isSpicy: false,
        menuItemNumber: 16,
        chineseTranslation: "锅云吞",
      },
      {
        id: 20,
        name: "Minced Beef and Egg White Soup",
        price: 11.95,
        isSpicy: false,
        menuItemNumber: 17,
        chineseTranslation: "西湖牛肉羹",
      },
      {
        id: 21,
        name: "Seafood and Dry Scallop Soup",
        price: 13.8,
        isSpicy: false,
        menuItemNumber: 18,
        chineseTranslation: "瑶柱海黄羹",
      },
      {
        id: 22,
        name: "Assorted Seafood and Tofu Soup (Large)",
        price: 19.8,
        isSpicy: false,
        menuItemNumber: 19,
        chineseTranslation: "海鲜豆腐汤",
      },
    ],
  },
  {
    menuSectionName: "CHINESE HERE - BEEF AND PORK 牛，猪肉类",
    menuSectionItems: [
      {
        id: 23,
        name: "Sliced Pork Sauteed with Cabbage",
        price: 15.95,
        isSpicy: true,
        menuItemNumber: 20,
        chineseTranslation: "回锅肉",
      },
      {
        id: 24,
        name: "Shredded Pork with Hot Garlic Sauce",
        price: 14.95,
        isSpicy: true,
        menuItemNumber: 21,
        chineseTranslation: "鱼香肉丝",
      },
      {
        id: 25,
        name: "Sweet-and-Sour Pork with Pineapple",
        price: 13.95,
        isSpicy: false,
        menuItemNumber: 22,
        chineseTranslation: "菠萝甜酸猪",
      },
      {
        id: 26,
        name: "Sweet-and-Sour Pork (Boneless)",
        price: 13.95,
        isSpicy: false,
        menuItemNumber: 23,
        chineseTranslation: "咕噜肉",
      },
      {
        id: 27,
        name: "Honey Garlic Boneless Pork",
        price: 15.95,
        isSpicy: false,
        menuItemNumber: 24,
        chineseTranslation: "京都肉排",
      },
      {
        id: 29,
        name: "Mandarin Pork Chops",
        price: 15.95,
        isSpicy: false,
        menuItemNumber: 25,
        chineseTranslation: "京都肉排",
      },
      {
        id: 30,
        name: "Deep-Fried Spicy Pork Chops",
        price: 15.75,
        isSpicy: true,
        menuItemNumber: 26,
        chineseTranslation: "椒盐肉排",
      },
      {
        id: 31,
        name: "Dry Garlic Spareribs",
        price: 13.95,
        isSpicy: false,
        menuItemNumber: 27,
        chineseTranslation: "蒜子干骨",
      },
      {
        id: 32,
        name: "Deep-Fried Spicy Dry Spareribs",
        price: 13.95,
        isSpicy: true,
        menuItemNumber: 28,
        chineseTranslation: "椒盐干骨",
      },
      {
        id: 33,
        name: "Steamed Spareribs in Black Bean Sauce",
        price: 16.25,
        isSpicy: false,
        menuItemNumber: 29,
        chineseTranslation: "豉汁蒸排骨",
      },
      {
        id: 34,
        name: "Steamed Pork Patty with Salted Fish",
        price: 15.95,
        isSpicy: false,
        menuItemNumber: 30,
        chineseTranslation: "咸鱼蒸肉饼",
      },
      {
        id: 35,
        name: "Sliced Beef with Black Bean Sauce",
        price: 15.95,
        isSpicy: false,
        menuItemNumber: 31,
        chineseTranslation: "豉汁牛肉",
      },
      {
        id: 36,
        name: "Stir-Fried Beef with Green Onions",
        price: 15.95,
        isSpicy: false,
        menuItemNumber: 32,
        chineseTranslation: "姜葱牛肉",
      },
      {
        id: 37,
        name: "Beef with Satay Sauce",
        price: 14.95,
        isSpicy: false,
        chineseTranslation: "沙爹牛肉",
        menuItemNumber: 33,
      },
      {
        id: 38,
        name: "Curried Beef",
        price: 14.75,
        isSpicy: true,
        chineseTranslation: "咖喱牛肉",
        menuItemNumber: 34,
      },
      {
        id: 39,
        name: "Pan-Fried Beef Tenderloin with Gourmet Sauce",
        price: 16.95,
        isSpicy: false,
        chineseTranslation: "中式牛柳",
        menuItemNumber: 35,
      },
      {
        id: 40,
        name: "Pan-Fried Beef Tenderloin with Black Pepper Sauce",
        price: 16.95,
        isSpicy: true,
        chineseTranslation: "黑椒牛柳",
        menuItemNumber: 36,
      },
      {
        id: 41,
        name: "Shredded Beef with Ginger Sauce",
        price: 14.75,
        isSpicy: false,
        chineseTranslation: "姜汁牛柳师",
        menuItemNumber: 37,
      },
      {
        id: 42,
        name: "Mongolian Beef",
        price: 15.95,
        isSpicy: false,
        chineseTranslation: "蒙古牛肉",
        menuItemNumber: 38,
      },
      {
        id: 43,
        name: "Beef with Broccoli",
        price: 13.95,
        isSpicy: false,
        chineseTranslation: "百家利牛肉",
        menuItemNumber: 39,
      },
      {
        id: 44,
        name: "Beef with Gai Lai (Chinese Broccoli)",
        price: 15.95,
        isSpicy: false,
        chineseTranslation: "芥蘭牛肉",
        menuItemNumber: 40,
      },
      {
        id: 100,
        name: "",
        price: 16.98,
        isSpicy: false,
        chineseTranslation: "农家小炒肉",
        menuItemNumber: 41,
      },
      {
        id: 45,
        name: "Beef with Oyster Sauce",
        price: 15.95,
        isSpicy: false,
        chineseTranslation: "蚝油牛肉",
        menuItemNumber: 42,
      },
      {
        id: 46,
        name: "Beef with Tomatoes",
        price: 14.95,
        isSpicy: false,
        chineseTranslation: "番茄牛肉",
        menuItemNumber: 43,
      },
      {
        id: 47,
        name: "Beef with Snow Peas",
        price: 15.95,
        isSpicy: false,
        chineseTranslation: "雪豆牛肉",
        menuItemNumber: 44,
      },
      {
        id: 48,
        name: "Beef Brisket with Daikon",
        price: 18.8,
        isSpicy: false,
        chineseTranslation: "萝卜牛腩",
        menuItemNumber: 45,
      },
      {
        id: 49,
        name: "Mixed Vegetable and Beef",
        price: 14.95,
        isSpicy: false,
        chineseTranslation: "杂菜牛肉",
        menuItemNumber: 46,
      },
      {
        id: 50,
        name: "Beef in Chili Sauce",
        price: 19.8,
        isSpicy: true,
        chineseTranslation: "水煮牛",
        menuItemNumber: 47,
      },
      {
        id: 51,
        name: "Sliced Beef with Green Bean in Black Bean Sauce",
        price: 15.95,
        isSpicy: false,
        chineseTranslation: "豉汁四季豆牛肉",
        menuItemNumber: 48,
      },
    ],
  },
  {
    menuSectionName: "CHINESE HERE - CHICKEN AND DUCK",
    menuSectionItems: [
      {
        id: 52,
        name: "Szechuan Chicken",
        price: 13.95,
        isSpicy: true,
        chineseTranslation: "chineseTranslation",
        menuItemNumber: 50,
      },
      {
        id: 53,
        name: "Curried Chicken",
        price: 14.5,
        isSpicy: true,
        chineseTranslation: "chineseTranslation",
        menuItemNumber: 51,
      },
      {
        id: 54,
        name: "Sliced Chicken with XO Sauce",
        price: 13.95,
        isSpicy: false,
        chineseTranslation: "chineseTranslation",
        menuItemNumber: 53,
      },
      {
        id: 55,
        name: "Deep Fried Chicken Wing",
        price: 12.95,
        isSpicy: false,
        chineseTranslation: "chineseTranslation",
        menuItemNumber: 54,
      },
      {
        id: 56,
        name: "Deep Fried Chicken Wings with Peppery Salt",
        price: 13.5,
        isSpicy: true,
        chineseTranslation: "chineseTranslation",
        menuItemNumber: 55,
      },
      {
        id: 57,
        name: "Deep Fried Breaded Almond Chicken",
        price: 13.95,
        isSpicy: false,
        chineseTranslation: "chineseTranslation",
        menuItemNumber: 56,
      },
      {
        id: 58,
        name: "Lemon Chicken",
        price: 14.95,
        isSpicy: false,
        chineseTranslation: "chineseTranslation",
        menuItemNumber: 57,
      },
      {
        id: 59,
        name: "Chicken in Black Bean Sauce",
        price: 13.95,
        isSpicy: false,
        chineseTranslation: "chineseTranslation",
        menuItemNumber: 58,
      },
      {
        id: 60,
        name: "Crispy Skin Chicken (Half)",
        price: 13.95,
        isSpicy: false,
        chineseTranslation: "chineseTranslation",
        menuItemNumber: 59,
      },
      {
        id: 61,
        name: "Crispy Skin Chicken (Whole)",
        price: 22.95,
        isSpicy: false,
        chineseTranslation: "chineseTranslation",
        menuItemNumber: 59,
      },
      {
        id: 62,
        name: "BBQ Duck (Half)",
        price: 16.95,
        isSpicy: false,
        chineseTranslation: "chineseTranslation",
        menuItemNumber: 60,
      },
      {
        id: 63,
        name: "BBQ Duck (Whole)",
        price: 28.95,
        isSpicy: false,
        chineseTranslation: "chineseTranslation",
        menuItemNumber: 60,
      },
      {
        id: 64,
        name: "Sweet and Sour Chicken Balls",
        price: 13.75,
        isSpicy: false,
        chineseTranslation: "chineseTranslation",
        menuItemNumber: 62,
      },
      {
        id: 65,
        name: "Diced Chicken with Vegetable and Cashew Nuts",
        price: 13.25,
        isSpicy: false,
        chineseTranslation: "chineseTranslation",
        menuItemNumber: 63,
      },
      {
        id: 66,
        name: "Kung Bo Chicken with Vegetable and Peanuts",
        price: 13.5,
        isSpicy: false,
        chineseTranslation: "chineseTranslation",
        menuItemNumber: 64,
      },
      {
        id: 67,
        name: "Empress Chicken (Half)",
        price: 15.95,
        isSpicy: false,
        chineseTranslation: "chineseTranslation",
        menuItemNumber: 65,
      },
      {
        id: 68,
        name: "Empress Chicken (Whole)",
        price: 28.8,
        isSpicy: false,
        chineseTranslation: "chineseTranslation",
        menuItemNumber: 65,
      },
      {
        id: 69,
        name: "Chicken with Pork Liver and Kidney Hot Pot",
        price: 17.8,
        isSpicy: false,
        chineseTranslation: "chineseTranslation",
        menuItemNumber: 66,
      },
    ],
  },
];
